name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write
  packages: write

jobs:
  build__ml_metadata_server:
    name: Build - ML Metadata Server
    uses: ./.github/workflows/build_image_TEMPLATE.yml
    secrets: inherit
    with:
      image_names: ghcr.io/${{ github.repository_owner }}/ml_metadata_store_server

      metadata_title: "ML-Metadata Server"
      metadata_description: "Google ML Metadata Server"

      tag_with_latest: false
      tag_with_semver: true
      tag_with_sha: false

      build_file: ./ml_metadata/tools/docker_server/Dockerfile
      build_context: .
      build_platforms: |-
        linux/amd64
        linux/arm64
      build_registry_cache: ghcr.io/${{ github.repository_owner }}/ci/ml_metadata_store_server:build-cache

      login_to_ghcr: true
      login_to_docker: false

  create_release:
    runs-on: ubuntu-latest
    needs: [ build__ml_metadata_server ]
    steps:
      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            const { repo: { owner, repo }, ref: tag_ref } = context;
            const tag_name = tag_ref.replace('refs/tags/', '');
            const tag_version = tag_ref.replace('refs/tags/v', '');

            // Create a release
            const response = await github.rest.repos.createRelease({
              owner: owner,
              repo: repo,
              tag_name: tag_name,
              name: `ML Metadata Server - ${tag_version}`,
              draft: false,
              // NOTE: for this repo, we always have '-patch.X' in the tag name
              //prerelease: tag_name.includes('-'),
            });